//generate short link
export const ADD_LINK = "ADD_LINK";
export const ADD_LINK_REQUEST = "ADD_LINK_REQUEST";
export const ADD_LINK_SUCCESS = "ADD_LINK_SUCCESS";
export const ADD_LINK_FAILURE = "ADD_LINK_FAILURE";

//get top 10 link access

export const GET_TOP_LINK = "GET_TOP_LINK";
export const GET_TOP_LINK_REQUEST = "GET_TOP_LINK_REQUEST";
export const GET_TOP_LINK_SUCCESS = "GET_TOP_LINK_SUCCESS";
export const GET_TOP_LINK_FAILURE = "GET_TOP_LINK_FAILURE";

//auth
export const CLIENT_SET = "CLIENT_SET";
export const CLIENT_UNSET = "CLIENT_UNSET";
export const LOGIN_REQUESTING = "LOGIN_REQUESTING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_EXISTING = "LOGIN_EXISTING";
export const LOGOUT = "LOGOUT";
export const UPDATE_AVATAR = "UPDATE_AVATAR";

export const REGISTER_REQUESTING = "REGISTER_REQUESTING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_EXISTING = "REGISTER_EXISTING";
//experiences

export const LOAD_TAGS = "LOAD_TAGS";
export const COMPLETE_LOAD_TAGS = "COMPLETE_LOAD_TAGS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER_REQUEST = "GET_CURRENT_USER_REQUEST";
export const RESET_COUNT_NOTIFI_REQUEST = "RESET_COUNT_NOTIFI_REQUEST";
export const RESET_COUNT_NOTIFI = "RESET_COUNT_NOTIFI";
export const SET_COUNT_NOTIFI = "SET_COUNT_NOTIFI";
